### PR TITLE
[#2547] Support reading of ECC private keys from PKCS#8 PEM files.

### PR DESCRIPTION
**Pull request by sophokles73**
The KeyStoreHelper has been extended to check the key algorithm
identifier provided in the ASN.1 structure and either use the RSA or the
EC KeyFactory to instantiate the private key.

### CODE REVIEW

**Comment by vietj** [comment]
it looks great, I think we need to update the documentation to list the supported format for PKCS8 too

**Comment by vietj** [comment]
the CI shows that the code does not build, can you check on your side ?

**Comment by sophokles73** [comment]
@vietj 

running `mvn clean install` on my local machine fails with:
```
Results :

Tests in error: 
  ConnectionPoolTest.testStress:581->AsyncTestBase.assertWaitUntil:606->AsyncTestBase.assertWaitUntil:619 » IllegalState

Tests run: 3834, Failures: 0, Errors: 1, Skipped: 31

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:35 min
[INFO] Finished at: 2019-03-11T17:10:37+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project vertx-core: There are test failures.
```

doesn't look like it's connected to my changes. The unit tests that I have added succeed when running locally ...

**Comment by sophokles73** [comment]
The docs already claim support for reading keys from PKCS#1 and PKCS#8 PEM files. However, it should probably be added that EC keys can only be read from PKCS#8 PEM files. I will give it a shot ...

**Comment by vietj** [comment]
the CI shows this:

```
[ERROR] /home/travis/build/eclipse-vertx/vert.x/src/main/java/io/vertx/core/net/impl/pkcs1/PrivateKeyParser.java:[75,16] constructor PKCS8EncodedKeySpec in class java.security.spec.PKCS8EncodedKeySpec cannot be applied to given types;
  required: byte[]
  found: byte[],java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /home/travis/build/eclipse-vertx/vert.x/src/main/java/io/vertx/core/net/impl/pkcs1/PrivateKeyParser.java:[77,16] constructor PKCS8EncodedKeySpec in class java.security.spec.PKCS8EncodedKeySpec cannot be applied to given types;
  required: byte[]
  found: byte[],java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /home/travis/build/eclipse-vertx/vert.x/src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java:[331,60] cannot find symbol
  symbol:   method getAlgorithm()
  location: variable keySpec of type java.security.spec.PKCS8EncodedKeySpec
[ERROR] /home/travis/build/eclipse-vertx/vert.x/src/main/java/io/vertx/core/net/impl/KeyStoreHelper.java:[334,63] cannot find symbol
  symbol:   method getAlgorithm()
  location: variable keySpec of type java.security.spec.PKCS8EncodedKeySpec
```

https://api.travis-ci.org/v3/job/504755653/log.txt

**Comment by sophokles73** [comment]
Ah, shoot, the two argument constructor is only available in Java versions > 8. I will have to refactor this ...

**Comment by sophokles73** [comment]
@vietj ok, seems to pass now ...

**Comment by sophokles73** [comment]
@vietj anything else I need to change?

**Comment by vietj** [comment]
looks good, I think we should add in documentation that we do not support PKCS8 encrypted private keys to avoid confusion

**Comment by sophokles73** [comment]
@vietj WDYT?

**Pull request merged**
