### PR TITLE
Issue3856

### PR DESCRIPTION
**Pull request by dratler**
Motivation:
Add lock and tryLock as requested #3856
Explain here the context, and why you're making that change, what is the problem you're trying to solve.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by dratler** [comment]
Hi @vietj ,
I have closed the old PR here is the new one I have re signed the eca still issue remains

**Comment by knotenpunkt** [comment]
@vietj @dratler do not only have the github email-adress the signing adress but also the commit-email-adress?

**Comment by vietj** [comment]
can you avoid reformatting what does not need to be reformated ?

**Comment by tsegismont** [comment]
Superseded by https://github.com/eclipse-vertx/vert.x/pull/4311

**Pull request closed without merging**
