### PR TITLE
Improved path normalization and URI decoding

### PR DESCRIPTION
**Pull request by franz1981**
Http parsing and Vertx-web routing can improve performance on common path.

This changes:
- makes `decodeURIComponent` inlinable (but moving away unlikely paths)
- speedup `decodeURIComponent`  for the `plus = false` case, leveraging on `indexOf(char)` intrinsic (see https://chriswhocodes.com/hotspot_intrinsics_openjdk11.html)
- speedup string concatenation on `normalizePath` with https://bugs.openjdk.org/browse/JDK-8085796
- speedup `normalizePath` adding a zero garbage fast-path and reducing bytecode size

### CODE REVIEW

**Comment by franz1981** [comment]
This is still in draft because I would like to add a microbenchmark (or check if any exists yet) on this

**Comment by franz1981** [comment]
@vietj This should make Techempower Plaintext (I didn't tried JSON) vertx-web similar to vertx; and it's obviously helping Quarkus in the common path too

**Comment by franz1981** [comment]
it's in draft just because I didn't yet write any JMH bench; if you want I can attach it here or in a separate PR and undraft this.

**Comment by pmlopes** [comment]
@franz1981 @vietj this code is used extensively on vertx-web, please double-check that all tests still pass there too.

**Comment by franz1981** [comment]
I can undraft this @pmlopes @vietj : both test suites are happy with this, yay!

**Comment by Sanne** [comment]
Really nice! Looking forward to getting this in Quarkus :)

**Review by vietj — APPROVED** [review]

**Comment by vietj** [comment]
thanks for the contribution @franz1981

**Comment by geoand** [comment]
More throughput for the entire stack, awesome!

**Pull request merged**
