### PR TITLE
Fix a typo in the javadoc for HttpConnection.localAddress

### PR DESCRIPTION
**Pull request by Apache9**
This is my first time to make use of vertx to implement a web server and this comment was confusing me a bit...

### CODE REVIEW

**Comment by vietj** [comment]
can you sign the Eclipse agreement to accept your commit ?

**Comment by Apache9** [comment]
> can you sign the Eclipse agreement to accept your commit ?

Sure. Let me see how to do this...

**Comment by Apache9** [comment]
When creating the eclipse account, it keeps telling me that my answer to the CAPTCHA is wrong, but I just can not see where is the CAPTCHA picture and the input form...

Will try again later...

**Comment by Apache9** [comment]
OK, I signed the CLA with palomino219@gmail.com and changed the emails in the commit message to this one. Seems fine?

@vietj PTAL. Thanks.

**Comment by Apache9** [comment]
Is there any other thing I need to do? @vietj 

Thanks.

**Comment by vietj** [comment]
no, it's very fine now

**Comment by vietj** [comment]
thank you

**Pull request merged**
