### PR TITLE
add lock and try lock

### PR DESCRIPTION
**Pull request by dratler**
Motivation:
Add lock and tryLock as requested https://github.com/eclipse-vertx/vert.x/issues/3856
Explain here the context, and why you're making that change, what is the problem you're trying to solve.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by dratler** [comment]
Hi @vietj ,
I have signed  the eca after the PR.
what else is missing ?

**Comment by vietj** [comment]
@dratler can you update the PR because now there are merge errors

**Comment by dratler** [comment]
Hi @vietj ,
I think I have completed the CR.
lately I have started getting failure on my build, at sections I haven't touched and I'm not sure how to handle.
can you advice please ?

**Comment by vietj** [comment]
you need to sign the Eclipse Contributor Agreement @dratler

**Comment by dratler** [comment]
Hi @vietj ,
I signd it again 
image

**Comment by vietj** [comment]
are you using the same email in your commit than in the ECA ?

**Comment by dratler** [comment]
yes,
but I'm getting 
image
I checked my email on the ECA and GitHub is the same

**Comment by vietj** [comment]
can you try a clean new PR ?

**Comment by dratler** [comment]
Following a request to Close this PR and try again

**Pull request closed without merging**
