### PR TITLE
Fix File resolver when classloader provides URLs for directories

### LINKED ISSUE #4660: WebSocket fetch and ping / pong
### Version

4.4.1

### Context

In looking at the fabric8 integration of vert.x we are using pause / fetch on websockets to control the rate at which messages are processed.  However it appears that ping / pong messages from the server count towards the fetch.  We can workaround this by not sending pings ourselves, or if we ever need to, use a pongHandler to increase the fetch.  However if the server sends a ping since the ping handling is baked-in there's nothing we can do to increase the fetch.

### Do you have a reproducer?

```
    Vertx vertx = Vertx.vertx(new VertxOptions());
    HttpServer server = vertx.createHttpServer();

    server.webSocketHandler(sws -> {
      sws.writePing(Buffer.buffer("ping"));
      sws.writeTextMessage("some message");
    }).listen(8080);

    HttpClient client = vertx.createHttpClient();
    CompletableFuture<String> message = new CompletableFuture<String>();
    client.webSocket(8080, "localhost", "/").onSuccess(ws -> {
      ws.pause();

      // demand is used for the ping instead
      ws.fetch(1);

      ws.textMessageHandler(message::complete);
    });

    // never completes
    message.get();
```

If we remove the pause / fetch, this will complete as expected.

cc @vietj the current api server implementation does not send a ping, so this isn't an issue for fabric8 yet.  However the likely resolution of the upstream issue https://github.com/kubernetes/kubernetes/pull/116778 will include using ping / pong as the heartbeat mechanism for websockets, so we'll probably have to account for this eventually.

### LINKED ISSUE #4749: ThreadLocal::remove performance impacts
https://github.com/eclipse-vertx/vert.x/blob/04d4d65fb47a3db4cd8a320795a397f1ae678173/src/main/java/io/vertx/core/net/impl/pool/CombinerExecutor.java#L60 introduced to solve https://github.com/eclipse-vertx/vert.x/issues/4583 is not performant (for our use cases), see
https://github.com/smallrye/smallrye-context-propagation/issues/424#issuecomment-1600718621

A different mechanism or just using `FastThreadLocal`'s (to ve verified if they have the same impact) would solve it.

### LINKED ISSUE #5039: Type Pollution Scalability issue over Vertx/Netty HTTP 2 pipeline traversal
As reported (and fixed) at https://github.com/netty/netty/pull/12806, only `ChannelDuplexHandler`s in netty have been fixed to solve the infamous type pollution issue: by running an hello-world like test with HTTP 2 in quarkus and attaching https://github.com/RedHatPerf/type-pollution-agent to it, this case popup

```
2:      io.vertx.core.http.impl.VertxHttp2ConnectionHandler
Count:  32816944
Types:
        io.netty.handler.codec.http2.Http2Connection$Listener
        io.netty.channel.ChannelInboundHandler
        io.netty.channel.ChannelOutboundHandler
        io.netty.handler.codec.http2.Http2LifecycleManager
Traces:
        io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.addStream(DefaultHttp2Connection.java:805)
                class: io.netty.handler.codec.http2.Http2Connection$Listener
                count: 7912545
        io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357)
                class: io.netty.handler.codec.http2.Http2Connection$Listener
                count: 6228227
        io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:839)
                class: io.netty.channel.ChannelOutboundHandler
                count: 5488418
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                class: io.netty.channel.ChannelInboundHandler
                count: 5343287
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:486)
                class: io.netty.channel.ChannelInboundHandler
                count: 5172992
        io.netty.handler.codec.http2.DefaultHttp2Connection.removeStream(DefaultHttp2Connection.java:317)
                class: io.netty.handler.codec.http2.Http2Connection$Listener
                count: 1525703
        io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.addToActiveStreams(DefaultHttp2Connection.java:995)
                class: io.netty.handler.codec.http2.Http2Connection$Listener
                count: 1145767
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
                class: io.netty.channel.ChannelInboundHandler
                count: 1
        io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:123)
                class: io.netty.channel.ChannelOutboundHandler
                count: 1
        io.netty.handler.codec.http2.DefaultHttp2Connection.goAwayReceived(DefaultHttp2Connection.java:237)
                class: io.netty.handler.codec.http2.Http2Connection$Listener
                count: 1
        io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.lifecycleManager(DefaultHttp2ConnectionEncoder.java:62)
                class: io.netty.handler.codec.http2.Http2LifecycleManager
                count: 1
        io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:94)
                class: io.netty.channel.ChannelInboundHandler
                count: 1
--------------------------```
```
The first one in the chart is a false positive (meaning that we have a single concrete class in all the relevent code paths making the issue to disappear, optimized away by the JIT), hence I won't report it.

But this one is real, awaiting to be triggered by "normal" runtime condititions eg:
- if the user/vertx setup a pipeline which contains 1 more `io.netty.channel.ChannelInboundHandler`-only or  `io.netty.channel.ChannelOutboundHandler`-only types being used in the traces below:
```
        io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:839)
                class: io.netty.channel.ChannelOutboundHandler
                count: 5488418
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
                class: io.netty.channel.ChannelInboundHandler
                count: 5343287
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:486)
                class: io.netty.channel.ChannelInboundHandler
                count: 5172992
```
than `io.vertx.core.http.impl.VertxHttp2ConnectionHandler`'s type checks there, which are dormient (ie they are not happening), would start to happen, causing the klass's `secondary_super_cache` to ping pong among these, and hitting the issue at https://github.com/netty/netty/pull/12806#issuecomment-1259216902

In short, the problem arise because ` io.vertx.core.http.impl.VertxHttp2ConnectionHandler` is extending `Http2ConnectionHandler`'s which is transitively implementing both inbound/outbound handlers.

image

As usual; this seems a good fix which should happen within Netty, but I'm reporting here because is directly affecting us and Netty's `Http2ChannelDuplexHandler` TBH, being a duplex handler, doesn't seem affect (last famous words...).

Additionally, we do have other interfaces which the IntelliJ diagram seems to have forgotten (it's a bug???) ie `Http2FrameListener` and `Http2Connection.Listener` , but only the latter appear in the agent's report.

It doesn't seem harmful because the only implementor of `Http2Connection$Listener` seems `VertxHttp2ConnectionHandler` apart from an implementor within Netty which we don't use (because we don't use `Http2ChannelDuplexHandler`).

### PR DESCRIPTION
**Pull request by cescoffier**
Handle the case where the file resolver is used with a classloader that returns a URL for directories.

When unpackFromJarURL is called with a directory, the method throws an exception as the entry does not exist. We can detect the case by checking the length and not trying to retrieve the JarFile from the connection.

### CODE REVIEW

**Comment by vietj** [comment]
can we test this ? what's the reproducer ?

**Comment by cescoffier** [comment]
I have been trying to add a test but it's not that simple. Even when creating my own resolver I'm not able to reproduce.

However, since the introduction of Vert.x 4.5, we got multiple reports that webjars and mvnpm jars cannot be loaded anymore. It brokes lot of existing applications.

Here is one of the exception we have seen:

```
2024-02-02 15:19:28,058 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /_static/wc-chatbot/0.1.2/dist/wc-chatbot.js failed, error id: 24aae10e-d749-4380-b81b-79714ed67f28-1: io.vertx.core.VertxException: Unable to unpack file at path 'jar:file:///Users/clement/.m2/repository/org/mvnpm/wc-chatbot/0.1.2/wc-chatbot-0.1.2.jar!/META-INF/resources/_static/wc-chatbot/0.1.2/dist'
at io.vertx.core.file.impl.FileResolverImpl.unpackFromJarURL(FileResolverImpl.java:360)
at io.vertx.core.file.impl.FileResolverImpl.unpackUrlResource(FileResolverImpl.java:247)
at io.vertx.core.file.impl.FileResolverImpl.resolveFile(FileResolverImpl.java:170)
at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:929)
at io.vertx.core.file.impl.FileSystemImpl$20.perform(FileSystemImpl.java:1135)
at io.vertx.core.file.impl.FileSystemImpl$20.perform(FileSystemImpl.java:1133)
at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.handle(FileSystemImpl.java:1174)
at io.vertx.core.file.impl.FileSystemImpl$BlockingAction.handle(FileSystemImpl.java:1156)
at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:190)
at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276)
at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:209)
at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: JAR entry META-INF/resources/_static/wc-chatbot/0.1.2/dist not found in /Users/clement/.m2/repository/org/mvnpm/wc-chatbot/0.1.2/wc-chatbot-0.1.2.jar
at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:146)
at java.base/sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:92)
at io.vertx.core.file.impl.FileResolverImpl.unpackFromJarURL(FileResolverImpl.java:320)
... 18 more
```

Something that puzzled me is that these "jars" do not have a MANIFEST, they are just zips.

**Comment by vietj** [comment]
thanks @cescoffier can you port to master branch as well ?

**Comment by cescoffier** [comment]
Sure! Let me do that right away!

**Comment by cescoffier** [comment]
Port to master: https://github.com/eclipse-vertx/vert.x/pull/5093

**Pull request merged**
