### PR TITLE
Fix missing headers bug when using clustered event bus

### PR DESCRIPTION
**Pull request by dhermanson**
**Motivation:**

This pull request cherry-picks to `master` the commit from  #4664 made on the `4.x` branch that fixes an issue which caused missing headers under certain circumstances.

**Conformance:**

You should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by dhermanson** [comment]
@vietj That test failure seems unrelated to this change, does it not?

**Comment by EmadAlblueshi** [comment]
Hi, Any updates regarding this PR?

**Comment by tsegismont** [comment]
@EmadAlblueshi I've restarted the jobs and will merge after we get a fresh build. Thanks

**Comment by EmadAlblueshi** [comment]
@tsegismont Thanks

**Pull request merged**
