### PR TITLE
Add context to file upload handlers

### LINKED ISSUE #3629: [Regression] Vertx4 HttpServerRequest.uploadHandler() erases context.
I have a code snippet (link to the github repo below) that works on vertx4 milestone4, but not with vertx4 >= milestone5.
At first I thought it could be related to https://github.com/eclipse-vertx/vert.x/issues/3601, but this does not seem to be the case.

# Problem
Vertx context (`Vertx.currentContext()`) is lost inside `HttpServerRequest.uploadHandler()`

# Expected behavior
Vertx context (`Vertx.currentContext()`)  is kept inside `HttpServerRequest.uploadHandler()`

# Code example
```
public class MyHandler implements Handler<RoutingContext> {
    @Override
    public void handle(RoutingContext routingContext) {
        final HttpServerRequest event = routingContext.request().getDelegate();
        event.setExpectMultipart(true);

        Context context = Vertx.currentContext(); // Context is NOT null here
        event.uploadHandler(event1 -> {
            Single.create(new io.vertx.rx.java.SingleOnSubscribeAdapter<>(fut -> {
                Context context2 = Vertx.currentContext(); // Context2 is null here
            })).subscribe(o -> routingContext.end("check"));
        });

    }
}
```

As I said, with vertx4 milestone 4, both `context` and `context2` are *not* null, while from milestone 5 onward, `context2` is `null`.

# Github project with reproducible test
https://github.com/oscarfh/vertx-upload-handler-context
The test `ATest#start_server` will fail, but if you downgrade to vertx milestone 4, it passes.

### PR DESCRIPTION
**Pull request by oscarfh**
This fixes #3629 and #3711

### CODE REVIEW

**Comment by vietj** [comment]
we need to have a test for this, otherwise the regression might come again

**Comment by oscarfh** [comment]
I added the desired tests by checking the context on the file update handler.

**Comment by vietj** [comment]
thanks

**Comment by gregopet** [comment]
Is there a way to get a 4.0.1 snapshot version? We migrated to 4.0 and everything seemed to work but now we've found a blocker due to this bug and I'd rather not revert to the pre-4.0 version?

**Comment by oscarfh** [comment]
@gregopet we are in the same situation. We do not want to build it ourselves, nor build it from github, but you could use https://jitpack.io/ if you want to.

**Comment by gregopet** [comment]
Thank you, that looks very useful!

**Comment by vietj** [comment]
we plan to release 4.0.1 soon (next week)

**Comment by oscarfh** [comment]
This includes [changes in the rabbitmq client](https://github.com/vert-x3/vertx-rabbitmq-client/pull/117), right?

**Pull request merged**
