### PR TITLE
Avoid invoking SLF4J logger API with null parameters

### PR DESCRIPTION
**Pull request by tsegismont**
See #4582

Otherwise, we cannot delegate to loggers written in Kotlin (which does not allow null variable arguments).

### CODE REVIEW

**Comment by vietj** [comment]
can we have a test for that ?

**Comment by tsegismont** [comment]
We already have, it's only the implementation which changes

**Comment by vietj** [comment]
so tests were failing ?

**Comment by vietj** [comment]
ok I see

**Comment by tsegismont** [comment]
> so tests were failing ?

Only the windows build was failing, for some unrelated reason.

**Comment by tsegismont** [comment]
> ok I see

Ok to merge and backport then?

**Review by vietj — APPROVED** [review]

**Pull request merged**
