### PR TITLE
Reproduce issue https://github.com/eclipse-vertx/vert.x/issues/4618

### PR DESCRIPTION
**Pull request by Sgitario**
Relates to https://github.com/eclipse-vertx/vert.x/issues/4618

### CODE REVIEW

**Comment by Sgitario** [comment]
About the options to fix the issue:
- Create a Http2ClientRequest for `HTTP/2`, and the existing HttpClientRequest for `HTTP/1.1`. So, if HttpClientRequest is received, the upgrade operation will always be performed. 
- Or always perform the upgrade operation if (for example) the headers are not HTTP/2 compliant

@vietj

**Comment by vietj** [comment]
can I ask why you are setting the request URI to empty ?

it is not allowed and Netty will translate the empty URI into "/" when it happens. (see https://www.rfc-editor.org/rfc/rfc2616#section-5.1.2 : _Note that the absolute path
   cannot be empty; if none is present in the original URI, it MUST be
   given as "/" (the server root)._)

Netty does not do it for HTTP/2, so I believe that Vert.x should automatically translate the empty URI into "/" to avoid this situation and have the same behaviour.

**Comment by vietj** [comment]
ah you are setting to empty to reproduce the situation, I think vertx should translate it to "/"

**Comment by vietj** [comment]
fixed

**Pull request closed without merging**
