### PR TITLE
Client proxy enhancements

### PR DESCRIPTION
**Pull request by vietj**
- nonProxyHost support
- per HTTP request / WebSocket proxy options

### CODE REVIEW

**Comment by vietj** [comment]
@vsevel @cescoffier here is the proxy support enhancements for 4.1, do you mind having a look ?

**Comment by vietj** [comment]
@vsevel @cescoffier can you check this PR responds to the issue appropriately ?

**Review by cescoffier — APPROVED** [review]
LGTM, but I don't have a complete understanding of the root (Vault) issue.

**Comment by vsevel** [comment]
could not get @fmarissel to validate the feature. whenever vertx 4.1 is available in quarkus, I will expose the new `nonProxyHost` property in the vault's config, in the context of https://github.com/quarkusio/quarkus/issues/16453

**Pull request merged**
