### PR TITLE
Fix #3077 call endHandler for HttpServerResponse without keepalive

### LINKED ISSUE #3077: http response endHandler not called on request with `connection: close`
After upstepping from vert.x version 3.6.2 to 3.7.1 we noticed that the endHandler for http 1.1 responses is not called anymore when the client asks for the connection to be closed with a `connection: close` header.

We can reproduce the issue with the following test in `io.vertx.core.http.HttpTest`:
```java
  @Test
  public void testResponseEndHandlersConnectionClose() {
    waitFor(2);
    server.requestHandler(req -> {
      req.response().endHandler(v -> complete());
      req.response().end();
    }).listen(onSuccess(server ->
      client.request(HttpMethod.GET, DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, "/", onSuccess(res -> {
        assertEquals(200, res.statusCode());
        complete();
      }))
      .putHeader(HttpHeaders.CONNECTION, "close")
      .end()));
    await();
  }
```

A `git bisect` points to 645f6d4 by @vietj.
As this is a rather big change it is unclear to us where it is introduced exactly.

### PR DESCRIPTION
**Pull request by steven-aerts**
This is a possible fix for #3077.

We are not confident at all that this is the correct fix, so please review carefully.
Although the tests seem to accept it.

### CODE REVIEW

**Comment by steven-aerts** [comment]
So travis ran three times for the proposed commit.
And only one time it failed with the below stacktrace.

Is this a known spurious issue, or can it triggered by this PR?

```
Starting test: Http1xTest#testHttpServerWithIdleTimeoutSendChunkedFile 
NULL 
java.nio.channels.ClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:604)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:621)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:605)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:467)
	at io.vertx.core.net.impl.ConnectionBase.handleIdle(ConnectionBase.java:324)
	at io.vertx.core.net.impl.VertxHandler.lambda$userEventTriggered$5(VertxHandler.java:179)
	at io.vertx.core.impl.EventLoopContext.schedule(EventLoopContext.java:45)
	at io.vertx.core.impl.AbstractContext.schedule(AbstractContext.java:103)
	at io.vertx.core.net.impl.VertxHandler.userEventTriggered(VertxHandler.java:179)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:327)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.timeout.IdleStateHandler.channelIdle(IdleStateHandler.java:372)
	at io.netty.handler.timeout.IdleStateHandler$AllIdleTimeoutTask.run(IdleStateHandler.java:578)
	at io.netty.handler.timeout.IdleStateHandler$AbstractIdleTask.run(IdleStateHandler.java:477)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

io.vertx.core.VertxException: Connection was closed
```

**Comment by vietj** [comment]
the test you are referring is not 100% reliable and should be improved that's why it can fail sometimes in CI

**Comment by vietj** [comment]
so the test for the new behavior works for HTTP/2 as well ?

**Comment by steven-aerts** [comment]
Yes it does.  (verified locally and in travis)

**Comment by vietj** [comment]
I reran CI and it passes, thanks for the fix, I'll merge it and backport to 3.8

**Comment by vietj** [comment]
thanks for the contribution @steven-aerts

**Pull request merged**
