### PR TITLE
Race condition in NetServer connection management

### LINKED ISSUE #2922: NullPointerException on Clustered EventBus
```
[{}] 2019-04-23 18:17:34.404 ERROR [vert.x-eventloop-thread-0] VertxFactory:lambda$null$0:44 - VertX Exception ->
java.lang.NullPointerException: null
	at io.vertx.core.net.impl.NetServerImpl.lambda$connected$13(NetServerImpl.java:471) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:188) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:180) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.net.impl.NetServerImpl.connected(NetServerImpl.java:467) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.net.impl.NetServerImpl.access$200(NetServerImpl.java:54) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.vertx.core.net.impl.NetServerImpl$1.initChannel(NetServerImpl.java:216) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:472) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.vertx.core.net.impl.VertxEventLoopGroup.register(VertxEventLoopGroup.java:53) ~[vertx-core-3.7.0.jar:3.7.0]
	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:254) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) ~[netty-all-4.1.5.Final.jar:4.1.5.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #2922

When a connection is established, a Vert.x handler is created and added to the channel pipeline.
The internal NetSocketImpl object is created only when the handler added event is fired, but it might not always happen immediately.

### CODE REVIEW

**Comment by vietj** [comment]
can you add a test ?

**Comment by tsegismont** [comment]
@vietj I'm not sure I can reproduce.

`io.vertx.core.net.impl.VertxHandler#getConnection` returns null when the `channelAdded` event is invoked asynchronously. This happens if:

1. a handler is added before the channel is registered, or
2. the channel handler context is created with a specific executor (different than the channel event loop)

(1) is not possible because `io.vertx.core.net.impl.NetServerImpl#connected` is invoked from `io.netty.channel.ChannelInitializer#initChannel`
(2) we don't do it

...

So perhaps it was Netty bug. In any case, it seems safer to make no assumptions about the behavior and move the code inside the `channelAdded` event handler.

**Comment by vietj** [comment]
agreed @tsegismont

**Comment by tsegismont** [comment]
Can you confirm it's ok to merge? (or approve changes)

**Pull request merged**
