### PR TITLE
Update index.adoc

### PR DESCRIPTION
**Pull request by d892fc**
Motivation:

Explain here the context, and why you're making that change, what is the problem you're trying to solve.

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by tsegismont** [comment]
Can you please sign the Eclipse Contributor Agreement?

**Comment by d892fc** [comment]
Thank you for your reply! I have already signed ECA, using d892fc@outlook.com.

**Comment by d892fc** [comment]
Thank you for your reply! I have already signed ECA, using d892fc@outlook.com. Please take a look.

**Comment by tsegismont** [comment]
Thanks, I just verified the ECA manually.

**Review by tsegismont — APPROVED** [review]

**Pull request merged**
