### PR TITLE
fix - remove ascii encoding from docs

### PR DESCRIPTION
**Pull request by kacperfronc**
Signed-off-by: Kacper Fronc <kacper.fronc@gmail.com>

Motivation:

There are a couple of ASCII encoded characters in docs - this removes them

### CODE REVIEW

**Comment by vietj** [comment]
can you sign the Eclipse contributor agreement ?

**Comment by kacperfronc** [comment]
Sure thing, did that - sorry

**Comment by kacperfronc** [comment]
@vietj 
I see that some tests failed but that seems unrelated. Could you confirm my assumption? I don't see an option to rerun tests

**Comment by vietj** [comment]
I'll run CI again

**Comment by vietj** [comment]
actually merged https://github.com/eclipse-vertx/vert.x/pull/3708 that does the same

**Pull request closed without merging**
