### PR TITLE
Make CLI options case sensitive for short names (#2844).

### PR DESCRIPTION
**Pull request by MitchAman**
Finally got around to addressing #2844.  Let me know if there's any formatting issues or anything like that - first time contributing in this code base.

### CODE REVIEW

**Comment by tsegismont** [comment]
@MitchAman thanks for sending a PR!

I just read the bug report and it says that currently the short names are compared ignoring case but not long names. But when I look at the code in master, both are compared ignoring case.

So to me, this doesn't look like a bug. But rather a request for changing behavior, that might impact users.

Also, in this PR, short names comparison has been made case-sensitive, while the long names one remained case-insensitive. If we change the current behavior, it should be changed consistently.

@MitchAman @vietj considering #2844 is not a bug but a change request, I believe we should decide if the benefits (ability to, for example, have `-a` and `-A` used for distinct options) outweigh the risks (users scripts with typos suddenly broken).

**Comment by MitchAman** [comment]
@tsegismont One potential mitigation for the risk of breaking user scripts would be to fall back to the case-insensitive behavior if there are no case-sensitivity conflicts.  This way if there's only an option for -a, then both -a and -A would still work, until a new option for -A is implemented.  That would make this more of a feature addition, rather than behavior change.

+1 on keeping short names and long names case-sensitivity behavior the same.

**Comment by vietj** [comment]
@tsegismont can you finish review this ?

**Comment by tsegismont** [comment]
@vietj will do tomorrow

**Comment by MitchAman** [comment]
@tsegismont Certainly, I'll try to get to that early next week.  Thanks for taking another look!

**Pull request merged**
