### PR TITLE
Future: Add new defaulted composeResult() method.

### PR DESCRIPTION
**Pull request by xkr47**
Allows mapping both success and failure results in one go.

No unit tests yet, probing for your interest in general first..

### CODE REVIEW

**Comment by xkr47** [comment]
Could perhaps also have a separate `andFinally(Runnable handler)` that has no async and no result-modifying capacity for simple cases..

**Comment by tsegismont** [comment]
How is this different from
io.vertx.core.Future#compose(java.util.function.Function<T,io.vertx.core.Future<U>>)
?

2017-04-08 23:47 GMT+02:00 Jonas Berlin <notifications@github.com>:

**Comment by xkr47** [comment]
> How is this different from `io.vertx.core.Future#compose(java.util.function.Function<T,io.vertx.core.Future<U>>)` ?

The function you give to compose() receives a `T` object as input if the future was successful, while the one you give to composeResult() receives a `AsyncResult<T>` object as input regardless of whether the future was successful or it failed.

The `AsyncResult<T>` contains methods with which you can retrieve the `T` object in case of success and also methods with which you can retrieve the Throwable in case of failure.

Thus, you can map both the success and failure cases in one go. For example you could implement a finally block like this:

```java
Future<Result> res = createTempFile("foo.tmp").compose((file) -> {
  return doSomethingWithFile(file).composeResult((asyncResult) -> {
    removeTempFile(file)
    return Future.future((fut) -> fut.handle(asyncResult));
  });
});
```

**Comment by tsegismont** [comment]
Your problem would be solved if you could write something like

Future<Result> res = createTempFile("foo.tmp").compose((file) -> {
  return doSomethingWithFile(file).whenComplete(removeTempFile(file));
});

Just like with CompletionStage/CompletableFuture

I'd recommend to use CS/CF instead of Vert.x future for this use case, or
the RxJava API.


2017-04-10 21:28 GMT+02:00 Jonas Berlin <notifications@github.com>:

**Comment by xkr47** [comment]
Are there plans to deprecate the vert.x Future etc classes in favour of java8 features?

**Comment by vietj** [comment]
@xkr47 not at the moment, we had a discussion about Java 8 CompletableFuture a few months ago, that you can read on vertx-dev list

**Comment by vietj** [comment]
done as https://github.com/eclipse-vertx/vert.x/commit/95f82b52bd68c28fe05c4cf0d2c9aaa88f358ced

**Comment by xkr47** [comment]
Ok great, works for me! :)

**Pull request closed without merging**
