### PR TITLE
Make sure metrics and cluster manager can be customized in Launcher

### LINKED ISSUE #3804: Cannot modify metrics options via sysprop or custom Launcher
A custom Launcher is often used when you want to setup things like metrics options programmatically before Vert.x is started.

Since #3771 , it is no longer possible to do this because the builder init method is invoked before the Launcher callback.

Then it's too late to customize the metrics implementation.

This applies to other special options too, I think (e.g. tracing, cluster manager).

EDIT: actually, it's no longer possible to activate some metrics options with sysprops. From Dropwizard docs:

```
-Dvertx.metrics.options.enabled=true -Dvertx.metrics.options.jmxEnabled=true
```

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #3804

### CODE REVIEW

**Comment by vietj** [comment]
the test fails is that expected ?

**Comment by tsegismont** [comment]
@vietj looking

**Comment by tsegismont** [comment]
@vietj PR updated, checks are all green (except the Windows one which is not finished yet)

**Comment by tsegismont** [comment]
@vietj rebased on master

**Comment by vietj** [comment]
before merging this, can you check it still works with
vertx-dropwizard-metrics ?

**Comment by tsegismont** [comment]
Yes it works.

**Pull request merged**
