### PR TITLE
using empty array for Collection.toArray()

### PR DESCRIPTION
**Pull request by dfa1**
Motivation:

There are two styles to convert a collection to an array: either using a pre-sized array (like c.toArray(new String[c.size()])) or using an empty array (like c.toArray(new String[0]).
    
In older Java versions using pre-sized array was recommended, as the reflection call which is necessary to create an array of proper size was quite slow. However since late updates of OpenJDK 6 this call was intrinsified, making the performance of the empty array version the same and sometimes even better, compared to the pre-sized version. Also passing pre-sized array is dangerous for a concurrent or synchronized collection as a data race is possible between the size and toArray call which may result in extra nulls at the end of the array, if the collection was concurrently shrunk during the operation.

### CODE REVIEW

**Comment by julianladisch** [comment]
The posted motivation text is the same as https://github.com/JetBrains/intellij-community/blob/master/plugins/InspectionGadgets/src/inspectionDescriptions/ToArrayCallWithZeroLengthArrayArgument.html and should have proper attribution.
For background information please visit https://shipilev.net/blog/2016/arrays-wisdom-ancients/

**Comment by dfa1** [comment]
thank you @julianladisch for your time, please have another look at the commit message

**Review by tsegismont — APPROVED** [review]
Thank you @dfa1

**Comment by dfa1** [comment]
you're welcome! I'm happy to contribute something back to the community :)

**Pull request merged**
