### PR TITLE
Fixes #3362 SslHandskaheTImeout is not applied on HttpServer

### LINKED ISSUE #3362: SslHandskaheTImeout is not applied on HttpServer

### PR DESCRIPTION
**Pull request by zenios**
Signed-off-by: Dimitris Zenios <dimitris.zenios@gmail.com>

### CODE REVIEW

**Comment by vietj** [comment]
can  you rebase the PR on the latest master I think one class got renamed - thanks

**Comment by zenios** [comment]
Sure

**Comment by zenios** [comment]
@vietj  done

**Comment by vietj** [comment]
can you do a PR back-port to 3.9 ?

**Comment by zenios** [comment]
Sure.will try later tonight.

**Comment by zenios** [comment]
https://github.com/eclipse-vertx/vert.x/pull/3381

Sorry for the delay

**Pull request merged**
