### PR TITLE
JsonArray methods for insertion of data at given position

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes https://github.com/vert-x3/issues/issues/488

### CODE REVIEW

**Comment by tsegismont** [comment]
Can you please review? Rx, Groovy and Kotlin modules build successfully with this change.

**Comment by vietj** [comment]
no tests ?

**Comment by tsegismont** [comment]
Yolo!

I'll try to add some today

**Comment by vietj** [comment]
wora

**Comment by tsegismont** [comment]
@vietj done

**Pull request merged**
