### PR TITLE
Improve JsonFactory creation and propagate its usage to DatabindCodec

### PR DESCRIPTION
**Pull request by mariofusco**
Motivation:

This pull request fixes both the remarks made [here](https://github.com/eclipse-vertx/vert.x/commit/dd6a58ee4aaeb88416b33d6fa8807495c4d3db59#r138410827) and [here](https://github.com/eclipse-vertx/vert.x/pull/5084#issuecomment-1932979506).

### CODE REVIEW

**Comment by vietj** [comment]
thanks, I like the simplification

**Comment by mariofusco** [comment]
> can you backport to 4.x branch ?

Sure, but if I'm not mistaken also [this commit](https://github.com/eclipse-vertx/vert.x/commit/dd6a58ee4aaeb88416b33d6fa8807495c4d3db59) has NOT being backported to 4.x branch. Should I backport both?

**Comment by vietj** [comment]
[The 4.x branch ](https://github.com/eclipse-vertx/vert.x/pull/5085)

**Comment by mariofusco** [comment]
@vietj see https://github.com/eclipse-vertx/vert.x/pull/5112

**Pull request merged**
