### PR TITLE
Typo in the text

### PR DESCRIPTION
**Pull request by toir427**
Typo in the text

### CODE REVIEW

**Comment by vietj** [comment]
can you sign the Eclipse agreement @toir427 ?

**Comment by toir427** [comment]
Yes. I did.

**Comment by toir427** [comment]
> can you sign the Eclipse agreement @toir427 ?

That’s why I need it. However, I signed up. Do I need drop the username here?

**Comment by vietj** [comment]
I'll merge it as is, as there is no code involved and you seem to have a valid eclipse account.

**Pull request merged**
