### PR TITLE
Use a long password on generated in-memory KeyStore

### PR DESCRIPTION
**Pull request by Nicolas-Duboc-IBM**
Motivation:

Fix for https://github.com/eclipse-vertx/vert.x/issues/4906

Hopefully trivial enough to have no wrong side-effect.

### CODE REVIEW

**Comment by vietj** [comment]
thanks, tests are failing with `KeyStoreHelperTest.testKeyStoreHelperSupportsPKCS8ECPrivateKey:68->assertKeyType:94 » UnrecoverableKey`

**Comment by Nicolas-Duboc-IBM** [comment]
> thanks, tests are failing with `KeyStoreHelperTest.testKeyStoreHelperSupportsPKCS8ECPrivateKey:68->assertKeyType:94 » UnrecoverableKey`

Hi.  I fixed the KeyStoreHelper tests in my latest commit.  Locally I have a couple of other failures on timeouts that look unrelated with this change.  Hopefully it runs better in the Github Actions build.

**Comment by Nicolas-Duboc-IBM** [comment]
Hi @vietj   Thank you for considering this fix for the 5.0 milestone.  Is there a chance to get this fix in a 4.4 release also ?  Should I propose a PR for a 4.4 branch ?

**Comment by vietj** [comment]
can you provide a PR for 4.x branch ?

**Comment by Nicolas-Duboc-IBM** [comment]
> can you provide a PR for 4.x branch ?

Here it is : https://github.com/eclipse-vertx/vert.x/pull/4910
Thanks !

**Pull request merged**
