### PR TITLE
Move to use lowercase header name instead

### PR DESCRIPTION
**Pull request by testn**
With HTTP/2, all the headers should be in lowercase form. By making all the headers to be lowercase, it will reduce the need for Netty/Vert.x to perform any conversion

Signed-off-by: Testo Nakada test1@doramail.com

### CODE REVIEW

**Comment by testn** [comment]
@vietj  got time to review it?

**Comment by vietj** [comment]
have you done study concerning the conversion ? with HTTP/1 and HTTP/2 ?

**Comment by testn** [comment]
Using lowercase is much more efficient for HTTP/2 AFAIK. For HTTP/1.1, it does not matter that much.

**Comment by vietj** [comment]
thanks, this was actually done differently but very similar, closing this

**Pull request closed without merging**
