### PR TITLE
Propagate trace when upgrading connections

### PR DESCRIPTION
**Pull request by Sgitario**
Fix https://github.com/eclipse-vertx/vert.x/issues/4630

### CODE REVIEW

**Comment by Sgitario** [comment]
fyi @vietj 
I tried to add a Vert.x test, but I could not reproduce it (the upgrade operation was not committed). However, I tried these changes using the Quarkus test and it worked fine now.

**Comment by vietj** [comment]
thanks @Sgitario what do you mean by not committed ?

**Comment by Sgitario** [comment]
> what do you mean by not committed ?

Where did you read "what do you mean by not committed" from me?

**Comment by Sgitario** [comment]
> thanks @Sgitario what do you mean by not committed ?

I mean that was not done. I found that if we restarted both the client and the server in the test, then the upgrade operation is done in the first request. Still, let me know if you want me to add a test and I will figure it out.

**Comment by vietj** [comment]
we should have a test @Sgitario can you provide that soon ?

**Comment by Sgitario** [comment]
> we should have a test @Sgitario can you provide that soon ?

PR updated with a test that reproduces this issue.
If you comment [this line](https://github.com/eclipse-vertx/vert.x/pull/4632/files#diff-fe5c92fbccf3b4aafaaea26628a7084280ef3f58a6076eeb042e67765f71f74eR146), the test will fail as expected.

**Comment by vietj** [comment]
@Sgitario nice! just in time for 4.4

**Pull request merged**
