### PR TITLE
Remove un-necessary Http1xServerConnection internal state synchronised access

### PR DESCRIPTION
**Pull request by vietj**
The `Http1xServerConnection` synchronize itself to guard the internal state of the request/response in progress.

Such synchronization used to be useful before Vert.x 4 and the clear dispatch between connection/request code. Currently read and writes are confined in the event-loop thread and removing this synchronization has no effect on the read/writes of this state.

### CODE REVIEW

**Comment by franz1981** [comment]
FYI:
https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/ResteasyReactiveOutputStream.java#L53

and check ` Http1xServerRequest` as well, which is still synchronizing over `conn` -> the connection

**Comment by vietj** [comment]
I think it should be fine for this case as we update the state of the request/response in progress and this sync and the request/close status which are not related to back-pressure/drain. WDYT ?

> FYI: https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/vertx/src/main/java/org/jboss/resteasy/reactive/server/vertx/ResteasyReactiveOutputStream.java#L53
> 
> and check ` Http1xServerRequest` as well, which is still synchronizing over `conn` -> the connection

**Comment by franz1981** [comment]
@vietj 

the best way would be to try running some of the tests on Quarkus which relies on it, by using a vertx version relax these properties @geoand @cescoffier how it looks?

**Comment by vietj** [comment]
which others do you mean ?

**Comment by franz1981** [comment]
> which others do you mean ?

Http1xServerRequest, for example

**Pull request merged**
