### PR TITLE
2934 make compressed http2 request possible

### PR DESCRIPTION
**Pull request by KowalczykBartek**
initial PR for https://github.com/eclipse-vertx/vert.x/issues/2934

### CODE REVIEW

**Comment by vietj** [comment]
can you sign the Eclipse Contributor Agreement and your commits ?

**Comment by KowalczykBartek** [comment]
@vietj did it change or something ? I signed it some time ago and my commits were merged - I am also surre that my commit is signed with my proper email

**Comment by vietj** [comment]
can you rebase this on 3.8 branch and resubmit @KowalczykBartek ?

**Comment by KowalczykBartek** [comment]
ok - will do that, but after work :)

**Comment by vietj** [comment]
thanks @KowalczykBartek eager to see that and review it for 3.8.3

**Comment by KowalczykBartek** [comment]
@vietj maybe we can close this ticket one and switch here https://github.com/eclipse-vertx/vert.x/pull/3141

**Pull request closed without merging**
