### PR TITLE
Add a close method to AsyncMultiMap

### PR DESCRIPTION
**Pull request by tsegismont**
This allows cluster managers to free resources they use to maintain the state.

Needed for vert-x3/issues#316

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj PTAL

**Comment by vietj** [comment]
how did it work before without a close method ?

**Comment by tsegismont** [comment]
> how did it work before without a close method ?

`ClusteredEventBus` just call it once. The problem would happen only if a user creates many multimaps for his own purposes.

**Comment by tsegismont** [comment]
> can we try instead to use java refs ?

Sorry I can't see what you mean... :(

**Comment by vietj** [comment]
weak references, look at NetClientImpl

**Comment by tsegismont** [comment]
Not sure how we could. We have to unregister listeners on the HZ map and
the ISPN cache. See the related cluster manager PRs

2018-01-10 16:40 GMT+01:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
I think you can on the map proxy itself as only the client has a ref to it, can't you ?

**Comment by tsegismont** [comment]
Sorry I don't understand. In any case, HZ or ISPN may still hold resources
related to the listener. So unregistering it seems mandatory

2018-01-10 16:52 GMT+01:00 Julien Viet <notifications@github.com>:

**Comment by tsegismont** [comment]
@vietj can you take another look before we close the 3.5.1 round? Thanks

**Comment by tsegismont** [comment]
vert-x3/issues#316 closed (won't fix)

**Pull request closed without merging**
