### PR TITLE
Set file cache dir to tmp

### PR DESCRIPTION
**Pull request by pmlopes**
As discussed on the thread: https://groups.google.com/forum/#!topic/vertx-dev/Gj_it5N7m34

Less pollution of working directory and make vert.x applications more container friendly where writing is usually not allowed, except on system temp dir.

### CODE REVIEW

**Comment by vietj** [comment]
cc @ludoch - while contributing the GAE Vert.x samples I needed to use a specific entry point to set the Vert.x cache base directory to `/tmp`. If we move this to `java.io.tmp` it believe this should work out of the box in GAE. Can you confirm ?

**Comment by vietj** [comment]
also I'm wondering if we should not port this to 3.7 as well.

**Comment by ludoch** [comment]
Hey,
On the Java11 GAE runtime I think we have the correct value for  java.io.tmpdir  to point  to  /tmp...

See some environment info in this live sample version:
https://gaeinfo-dot-openjdk11.appspot.com/

Now, remember that for us, /tmp is mapped to your memory, so it should not grow that much  over time, or you'll end up having Java OOM errors.

**Comment by vietj** [comment]
@pmlopes can you perform the change I asked so we can merge this PR ? also the eclipse check does not seem to pass, can you make a new PR to avoid this ?

**Comment by pmlopes** [comment]
This PR has been replaced by #2888 due to issues with eclipse validation

**Comment by vietj** [comment]
I'll back-port to 3.7 in the minute

**Comment by vietj** [comment]
@pmlopes can you add this to the breaking change wiki page for 3.7 ?

**Pull request closed without merging**
