### PR TITLE
Removed synchronization in shared net servers code

### LINKED ISSUE #3142: Deadlock when deploying several instances of a verticle a starting net server
This is a regression on 3.8.2 due to #3117

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #3142

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj please take a look, this is a fix that may be included in 3.8.3. Thanks!

**Comment by vietj** [comment]
can you explain what it does fix and post the deadlock trace ?

**Comment by vietj** [comment]
I've rewritten `AsyncResultConnect` helper in a branch to use Netty promises which avoid to maintain a list of handlers, we should try it to see if it fixes the issue instead of adding more complexity to this class

**Comment by vietj** [comment]
here is the code of the `AsyncResolveConnectHelper`:

```
/*
 * Copyright (c) 2011-2017 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
 * which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 */

package io.vertx.core.net.impl;

import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.util.concurrent.Promise;
import io.vertx.core.impl.VertxInternal;
import io.vertx.core.net.SocketAddress;

import java.net.InetSocketAddress;

/**
 * @author <a href="http://tfox.org">Tim Fox</a>
 */
public class AsyncResolveConnectHelper {

  private static void checkPort(int port) {
    if (port < 0 || port > 65535) {
      throw new IllegalArgumentException("Invalid port " + port);
    }
  }

  public static io.netty.util.concurrent.Future<Channel> doBind(VertxInternal vertx,
                                                                SocketAddress socketAddress,
                                                  ServerBootstrap bootstrap) {
    Promise<Channel> promise = vertx.getAcceptorEventLoopGroup().next().newPromise();
    bootstrap.channelFactory(vertx.transport().serverChannelFactory(socketAddress.path() != null));
    if (socketAddress.path() != null) {
      java.net.SocketAddress converted = vertx.transport().convert(socketAddress, true);
      ChannelFuture future = bootstrap.bind(converted);
      future.addListener(f -> {
        if (f.isSuccess()) {
          promise.setSuccess(future.channel());
        } else {
          promise.setFailure(f.cause());
        }
      });
    } else {
      checkPort(socketAddress.port());
      vertx.resolveAddress(socketAddress.host(), res -> {
        if (res.succeeded()) {
          // At this point the name is an IP address so there will be no resolve hit
          InetSocketAddress t = new InetSocketAddress(res.result(), socketAddress.port());
          ChannelFuture future = bootstrap.bind(t);
          future.addListener(f -> {
            if (f.isSuccess()) {
              promise.setSuccess(future.channel());
            } else {
              promise.setFailure(f.cause());
            }
          });
        } else {
          promise.setFailure(res.cause());
        }
      });
    }
    return promise;
  }
}
```

**Comment by vietj** [comment]
usage is pretty straightforward, here is excerpt from `NetServer`

```java
          bindFuture = AsyncResolveConnectHelper.doBind(vertx, localAddress, bootstrap);
          bindFuture.addListener((GenericFutureListener<io.netty.util.concurrent.Future<Channel>>) res -> {
            if (res.isSuccess()) {
              Channel ch = res.getNow();
              ...
            } else {
              ...
            }
```

**Comment by tsegismont** [comment]
> can you explain what it does fix and post the deadlock trace ?

With the test that is in this PR and without the fix proposed, I have seen two different cases. One that involves the `AsyncResolveConnectHelper`:

```
Found one Java-level deadlock:
=============================
"vert.x-eventloop-thread-7":
  waiting to lock monitor 0x00007f46080046e8 (object 0x00000000e8b78478, a java.util.HashMap),
  which is held by "vert.x-eventloop-thread-5"
"vert.x-eventloop-thread-5":
  waiting to lock monitor 0x00007f4608004798 (object 0x00000000e94615b0, a io.vertx.core.net.impl.AsyncResolveConnectHelper),
  which is held by "vert.x-eventloop-thread-4"
"vert.x-eventloop-thread-4":
  waiting to lock monitor 0x00007f46080046e8 (object 0x00000000e8b78478, a java.util.HashMap),
  which is held by "vert.x-eventloop-thread-5"

Java stack information for the threads listed above:
===================================================
"vert.x-eventloop-thread-7":
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:171)
	- waiting to lock <0x00000000e8b78478> (a java.util.HashMap)
	- locked <0x00000000e95110f0> (a io.vertx.core.net.impl.NetServerImpl)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:334)
	- locked <0x00000000e95110f0> (a io.vertx.core.net.impl.NetServerImpl)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:351)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:356)
	- locked <0x00000000e95110f0> (a io.vertx.core.net.impl.NetServerImpl)
	at io.vertx.core.SharedServersConcurrencyTest$NetVerticle.start(SharedServersConcurrencyTest.java:64)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
	at io.vertx.core.impl.DeploymentManager$$Lambda$25/525683462.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:178)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:40)
	at io.vertx.core.impl.EventLoopContext$$Lambda$26/1071097621.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
"vert.x-eventloop-thread-5":
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.addListener(AsyncResolveConnectHelper.java:37)
	- waiting to lock <0x00000000e94615b0> (a io.vertx.core.net.impl.AsyncResolveConnectHelper)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:277)
	- locked <0x00000000e8b78478> (a java.util.HashMap)
	- locked <0x00000000e949c220> (a io.vertx.core.net.impl.NetServerImpl)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:334)
	- locked <0x00000000e949c220> (a io.vertx.core.net.impl.NetServerImpl)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:351)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:356)
	- locked <0x00000000e949c220> (a io.vertx.core.net.impl.NetServerImpl)
	at io.vertx.core.SharedServersConcurrencyTest$NetVerticle.start(SharedServersConcurrencyTest.java:64)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:491)
	at io.vertx.core.impl.DeploymentManager$$Lambda$25/525683462.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:178)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:40)
	at io.vertx.core.impl.EventLoopContext$$Lambda$26/1071097621.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
"vert.x-eventloop-thread-4":
	at io.vertx.core.net.impl.NetServerImpl.lambda$listen$0(NetServerImpl.java:239)
	- waiting to lock <0x00000000e8b78478> (a java.util.HashMap)
	at io.vertx.core.net.impl.NetServerImpl$$Lambda$57/207484007.handle(Unknown Source)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.handle(AsyncResolveConnectHelper.java:51)
	- locked <0x00000000e94615b0> (a io.vertx.core.net.impl.AsyncResolveConnectHelper)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.lambda$null$2(AsyncResolveConnectHelper.java:89)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper$$Lambda$45/122371804.operationComplete(Unknown Source)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:982)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:567)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

And one that involves `NetServerImpl#actualPort()` (but I can't reproduce anymore now). Anyway, the same method on `HttpServerImpl` is no longer `synchronized`, which sounds legit given the field is `volatile`.

**Comment by tsegismont** [comment]
>I've rewritten AsyncResultConnect helper in a branch to use Netty promises which avoid to maintain a list of handlers, we should try it to see if it fixes the issue instead of adding more complexity to this class

I had not thought about that. Please go ahead and send another PR (take the test added here). I'll review it.

From my perspective the change proposed here removes rather than adds complexity (code is easier to read and avoids nesting synchronization). But anyway it looks like your idea will solve the issue in both a more efficient and more elegant manner.

**Comment by vietj** [comment]
I will test it and advise

**Comment by vietj** [comment]
tests are passing when I run them an high number of times (10000)

**Comment by vietj** [comment]
fixed by https://github.com/eclipse-vertx/vert.x/commit/3d7ee3ceebb9989484aafee240b25883a1d822d5

**Pull request closed without merging**
