### PR TITLE
Deprecate EventBusOptions delegates in VertxOptions

### LINKED ISSUE #2873: Deprecate EventBusOptions delegates in VertxOptions
We had a 2 days effort because the API is misleading:

	VertxOptions options = new VertxOptions()
		.setClustered(true)
		.setClusterHost("10.x.y.z")
		.setClusterPort(60000);
	
	System.out.println(options);
	
	options
		.setEventBusOptions(new EventBusOptions()
			.setSsl(true)
			.setKeyStoreOptions(new JksOptions())
		);
	
	System.out.println(options);

This will result in:

    VertxOptions{..., eventbus={"clustered":true,"host":"10.x.y.z","port":60000,"ssl":false, ...}
    VertxOptions{..., eventbus={"clustered":false,"host":"localhost","port":0,"ssl":true, ...}

But I expected:

    VertxOptions{..., eventbus={"clustered":true,"host":"10.x.y.z","port":60000,"ssl":false, ...}
    VertxOptions{..., eventbus={"clustered":true,"host":"10.x.y.z","port":60000,"ssl":true, ...}

In my opinion the API should be changed in order to reduce the confusion. If I configure an option it should not be changed after setting other options.

Workaround #1:

	VertxOptions options = new VertxOptions()
		// set event bus options at first
		.setEventBusOptions(new EventBusOptions()
			.setSsl(true)
			.setKeyStoreOptions(new JksOptions()))
		.setClustered(true)
		.setClusterHost("10.x.y.z")
		.setClusterPort(60000);

Workaround #2:

	VertxOptions options = new VertxOptions()
		.setClustered(true)
		.setClusterHost("10.x.y.z")
		.setClusterPort(60000);
	
	// do not overwrite event bus options but change the default one
	options.getEventBusOptions()
		.setSsl(true)
		.setKeyStoreOptions(new JksOptions());

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #2873

### CODE REVIEW

**Comment by tsegismont** [comment]
@vietj pushed this as discussed in #2883 . Will merge after validation from CI.

**Comment by vietj** [comment]
please check the entire stack when applying the removal in master

**Comment by vietj** [comment]
also we should remove deprecated usage in 3.7 stack too, mainly in unit tests I think

**Comment by tsegismont** [comment]
> please check the entire stack when applying the removal in master

Yes, master is another story.

Btw, 3.7 Ruby and JS langs need an update as well, given they have doc overrides using the deprecated methods.

> also we should remove deprecated usage in 3.7 stack too, mainly in unit tests I think

Will do

**Pull request merged**
