### PR TITLE
wmic deprecated in win10, replace with powershell command

### LINKED ISSUE #3385: wmic deprecated in win10
#### Describe the feature

In method io.vertx.core.impl.launcher.commands.StopCommand.terminateWindowsApplication:

```java
  private void terminateWindowsApplication() {
    // Use wmic.
    List<String> cmd = Arrays.asList(
        "WMIC",
        "PROCESS",
        "WHERE",
        "CommandLine like '%vertx.id=" + id + "%'",
        "CALL",
        "TERMINATE"
    );
```

since WMIC is about to sunset in future, and already deprecated in Win 10, one of our interns are using win 10 and found this issue, so should we use Get-CimInstance to replace it?

reference: [https://stackoverflow.com/questions/57121875/what-can-i-do-about-wmic-is-deprecated](https://stackoverflow.com/questions/57121875/what-can-i-do-about-wmic-is-deprecated)

#### Use cases

We are using Windows 10 & vertx-maven-plugin to build vert.x project and it breaks when redeploying the project using vertx-maven-plugin
while it works in macOS 

#### Contribution

@tsegismont may help solve this issue

original issue: https://github.com/reactiverse/vertx-maven-plugin/issues/205

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #3385

### CODE REVIEW

**Comment by tsegismont** [comment]
@chengenzhao can you please review and, if possible, test?

I tried on a virtual win10 machine on my box, it works for me.

@vietj did we have any plans to run some specific tests on a Windows CI?

**Comment by tsegismont** [comment]
Note that the fix requires Powershell, which is included in XP SP3+. I believe it is fine.

**Comment by vietj** [comment]
@tsegismont it seems that Travis can use windows images, so we would need a profile for this and a specific job for it

**Comment by vietj** [comment]
anyone can try this in his own fork of vert.x and travis

**Comment by vietj** [comment]
https://docs.travis-ci.com/user/reference/windows/ for reference

**Comment by vietj** [comment]
I hope we can get the appropriate image though

**Comment by tsegismont** [comment]
@vietj ok, I'll try to run a few tests in my own fork, then perhaps we can activate these in master builds

**Comment by tsegismont** [comment]
@vietj I had a look at Travis Windows support, it's going to be difficult to use. Java is not a supported language on Windows builds, so we'd have to install all the toolchain manually and then do fancy matrix config to have linux builds at the same time.
So if we want some tests to be run on Windows, it would be much easier to do it on Azure builds (there is a free plan for opensource).

In the meantime, I ran the relevant tests on my Win10 virtual machine (`StartStopListCommandsTest`) and it works fine. Manual testing with Vert.x Maven Plugin on this machine worked too.

**Comment by vietj** [comment]
can you try running with GitHub actions instead ?

**Comment by chengenzhao** [comment]
Hi:

@tsegismont thx for the contribution, it works for my win 10 computer.
It would be nice to have test run on Windows

Cheers

**Comment by tsegismont** [comment]
> can you try running with GitHub actions instead ?

You mean some tests on Windows only, right?

Also, can we make address the CI concern on a separate issue?

**Comment by vietj** [comment]
> On 27 Apr 2020, at 11:55, Thomas Segismont <notifications@github.com> wrote:
> 
> 
> can you try running with GitHub actions instead ?
> 
> You mean some tests on Windows only, right?
> 
> 

yes, I would like to test specific Windows behavior such as this one and also running file system tests.
> Also, can we make address the CI concern on a separate issue?
> 
> 

what is the CI concern ?

**Comment by tsegismont** [comment]
>what is the CI concern ?

I meant that addressing the `wmic` issue is a different concern than adding windows CI with GH actions

**Comment by vietj** [comment]
we are planning using windows CI in GH actions only for vertx-core, so it's not a general concern but it can be discussed separately indeed.

**Comment by tsegismont** [comment]
@vietj ok, I've added GH actions investigation to my tasks list. Merging this one now.

**Comment by tsegismont** [comment]
Roger that

Le ven. 29 mai 2020 à 21:27, Julien Viet <notifications@github.com> a
écrit :

**Pull request merged**
