### PR TITLE
Add cacheDirname to exception to help troubleshoot issue

### PR DESCRIPTION
**Pull request by rpelisse**

### CODE REVIEW

**Comment by vietj** [comment]
you need the eclipse agreement first and your PR - see the how to for contributing https://github.com/vert-x3/wiki/wiki/How-to-contribute-to-Vert.x

**Comment by rpelisse** [comment]
@vietj Can I simply file it against your fork (or some other fork) ? I feel a bit like I'm submitting a small against Linus Torvald repo rather than one of the lieutenant :)

@cescoffier or maybe yours?

**Comment by vietj** [comment]
no you can't

it won't solve the issue

we can do it for you though

**Comment by rpelisse** [comment]
Then please do! It's very small fix, I don't mind not being credited for it :) (it's just drove me yesterday to not have this piece of information, so...)

**Comment by vietj** [comment]
@rpelisse done

**Pull request closed without merging**
